# Generated by Django 3.1.1 on 2021-05-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210525_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
