# Generated by Django 3.0.8 on 2021-06-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210606_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe',
            new_name='stripe_charge',
        ),
    ]
