# Generated by Django 3.0.8 on 2021-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210611_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
