# Generated by Django 3.1.1 on 2021-05-25 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('province', models.CharField(choices=[('S', 'Sindh'), ('P', 'Punjab'), ('B', 'Balochistan'), ('K', 'Khyber PakhtunKhwa'), ('A', 'Azad Kashmir')], max_length=3)),
                ('city', models.CharField(max_length=200)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to=user.models.path_and_rename)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='user.address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
