# Generated by Django 3.0.8 on 2021-06-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210605_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(default=None, max_length=100,null=True),
        ),
    ]
